"""empty message

Revision ID: 09ee917e8ac7
Revises: fdb14687da3f
Create Date: 2021-04-05 13:44:25.874322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '09ee917e8ac7'
down_revision = 'fdb14687da3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_wallet_address'), 'user', ['wallet_address'], unique=False)
    op.create_table('miner',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userStat',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('est_revenue', sa.Float(), nullable=True),
    sa.Column('valid_shares', sa.Integer(), nullable=True),
    sa.Column('stale_shares', sa.Integer(), nullable=True),
    sa.Column('invalid_shares', sa.Integer(), nullable=True),
    sa.Column('round_share_percent', sa.Float(), nullable=True),
    sa.Column('effective_hashrate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'user_id')
    )
    op.create_table('gpu',
    sa.Column('miner_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('gpu_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['miner_id'], ['miner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('miner_id', 'gpu_no')
    )
    op.create_table('health',
    sa.Column('miner_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('gpu_no', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('hashrate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['miner_id', 'gpu_no'], ['gpu.miner_id', 'gpu.gpu_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('miner_id', 'gpu_no', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health')
    op.drop_table('gpu')
    op.drop_table('userStat')
    op.drop_table('miner')
    op.drop_index(op.f('ix_user_wallet_address'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
