"""added share stats per gpu

Revision ID: 121757096d4a
Revises: 745a4cf85c66
Create Date: 2021-05-17 15:54:22.140144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '121757096d4a'
down_revision = '745a4cf85c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('invalid_shares', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('valid_shares', sa.Integer(), nullable=True))
    op.alter_column('miner', 'user_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miner', 'user_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=False)
    op.drop_column('health', 'valid_shares')
    op.drop_column('health', 'invalid_shares')
    # ### end Alembic commands ###
