"""make user_id a primary key on a miner

Revision ID: 132eccb36282
Revises: 09ee917e8ac7
Create Date: 2021-04-05 16:33:26.842339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '132eccb36282'
down_revision = '09ee917e8ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miner', 'user_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miner', 'user_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=True)
    # ### end Alembic commands ###
