"""add a name column to miner

Revision ID: 68c1cef45ceb
Revises: 132eccb36282
Create Date: 2021-04-05 20:12:29.026506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c1cef45ceb'
down_revision = '132eccb36282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miner', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miner', 'name')
    # ### end Alembic commands ###
