"""added blacklist for jwt tokens

Revision ID: 745a4cf85c66
Revises: 68c1cef45ceb
Create Date: 2021-04-07 17:16:35.420245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745a4cf85c66'
down_revision = '68c1cef45ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
