"""empty message added more cols for gpu health

Revision ID: 83df110426c8
Revises: fefcf1b3babb
Create Date: 2021-06-09 21:40:49.385427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83df110426c8'
down_revision = 'fefcf1b3babb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('fan_speed', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('gpu_name', sa.String(), nullable=True))
    op.add_column('health', sa.Column('power_draw', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('power_limit', sa.Integer(), nullable=True))
    op.drop_column('health', 'hashrate')
    op.drop_column('health', 'power')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('health', sa.Column('hashrate', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    op.drop_column('health', 'power_limit')
    op.drop_column('health', 'power_draw')
    op.drop_column('health', 'gpu_name')
    op.drop_column('health', 'fan_speed')
    # ### end Alembic commands ###
