"""added gpu model name to table

Revision ID: c4fb73a3f4d5
Revises: 83df110426c8
Create Date: 2021-06-09 21:59:06.291742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fb73a3f4d5'
down_revision = '83df110426c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpu', sa.Column('gpu_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpu', 'gpu_name')
    # ### end Alembic commands ###
