"""added memory and core clock to health table

Revision ID: c76abf27c6be
Revises: a1aa05603efd
Create Date: 2021-06-14 21:06:25.849534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76abf27c6be'
down_revision = 'a1aa05603efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('core', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('memory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health', 'memory')
    op.drop_column('health', 'core')
    # ### end Alembic commands ###
