"""changed name of core and mem clock cols to be more descriptive

Revision ID: dd2a3eed1911
Revises: c76abf27c6be
Create Date: 2021-06-19 22:48:10.755059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2a3eed1911'
down_revision = 'c76abf27c6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('core_clock', sa.Integer(), nullable=True))
    op.add_column('health', sa.Column('mem_clock', sa.Integer(), nullable=True))
    op.drop_column('health', 'memory')
    op.drop_column('health', 'core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('core', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('health', sa.Column('memory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('health', 'mem_clock')
    op.drop_column('health', 'core_clock')
    # ### end Alembic commands ###
