"""created table for shares per gpu

Revision ID: fefcf1b3babb
Revises: 121757096d4a
Create Date: 2021-05-17 21:54:01.540308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fefcf1b3babb'
down_revision = '121757096d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('miner_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('gpu_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum(), nullable=False),
    sa.ForeignKeyConstraint(['miner_id', 'gpu_no'], ['gpu.miner_id', 'gpu.gpu_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'miner_id', 'gpu_no')
    )
    op.drop_column('health', 'invalid_shares')
    op.drop_column('health', 'valid_shares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health', sa.Column('valid_shares', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('health', sa.Column('invalid_shares', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('share')
    # ### end Alembic commands ###
